
// Code generated by stanc v2.30.1
#include <stan/model/model_header.hpp>
namespace prey_predator_draws2data_model_namespace {

using stan::model::model_base_crtp;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 36> locations_array__ = 
{" (found before start of program)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 15, column 4 to column 38)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 16, column 4 to column 40)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 17, column 4 to column 41)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 18, column 4 to column 38)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 19, column 4 to column 58)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 22, column 4 to column 25)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 23, column 4 to column 28)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 25, column 4 to column 30)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 26, column 4 to column 36)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 27, column 4 to column 40)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 29, column 4 to column 130)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 30, column 4 to column 51)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 31, column 4 to column 55)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 33, column 4 to column 72)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 34, column 4 to column 64)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 5, column 4 to column 12)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 9, column 4 to column 28)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 10, column 10 to column 13)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 10, column 4 to column 100)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 29, column 32 to column 35)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 30, column 10 to column 13)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 31, column 10 to column 13)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_functions.stan', line 3, column 4, included from\n'/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 2, column 0)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_functions.stan', line 6, column 4, included from\n'/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 2, column 0)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_functions.stan', line 7, column 4, included from\n'/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 2, column 0)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_functions.stan', line 9, column 4, included from\n'/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 2, column 0)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_functions.stan', line 10, column 4, included from\n'/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 2, column 0)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_functions.stan', line 11, column 4, included from\n'/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 2, column 0)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_functions.stan', line 12, column 4, included from\n'/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 2, column 0)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_functions.stan', line 13, column 4, included from\n'/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 2, column 0)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_functions.stan', line 14, column 4, included from\n'/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 2, column 0)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_functions.stan', line 16, column 4, included from\n'/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 2, column 0)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_functions.stan', line 17, column 4, included from\n'/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 2, column 0)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_functions.stan', line 19, column 4, included from\n'/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 2, column 0)",
 " (in '/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_functions.stan', line 2, column 96, included from\n'/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files/prey-predator_draws2data.stan', line 2, column 0)"};

struct vensim_ode_func_functor__ {
  template <typename T0__, typename T1__, typename T2__, typename T3__,
            typename T4__, typename T5__,
            stan::require_all_t<stan::is_stan_scalar<T0__>,
                                stan::is_col_vector<T1__>,
                                stan::is_vt_not_complex<T1__>,
                                stan::is_stan_scalar<T2__>,
                                stan::is_stan_scalar<T3__>,
                                stan::is_stan_scalar<T4__>,
                                stan::is_stan_scalar<T5__>>* = nullptr>
  Eigen::Matrix<stan::promote_args_t<T0__, stan::base_type_t<T1__>, T2__, T3__, T4__,
                       stan::promote_args_t<T5__>>, -1, 1>
  operator()(const T0__& time, const T1__& outcome, const T2__& delta,
             const T3__& beta, const T4__& alpha, const T5__& gamma,
             std::ostream* pstream__) const;
};
struct vensim_ode_func_odefunctor__ {
  template <typename T0__, typename T1__, typename T2__, typename T3__,
            typename T4__, typename T5__,
            stan::require_all_t<stan::is_stan_scalar<T0__>,
                                stan::is_col_vector<T1__>,
                                stan::is_vt_not_complex<T1__>,
                                stan::is_stan_scalar<T2__>,
                                stan::is_stan_scalar<T3__>,
                                stan::is_stan_scalar<T4__>,
                                stan::is_stan_scalar<T5__>>* = nullptr>
  Eigen::Matrix<stan::promote_args_t<T0__, stan::base_type_t<T1__>, T2__, T3__, T4__,
                       stan::promote_args_t<T5__>>, -1, 1>
  operator()(const T0__& time, const T1__& outcome, std::ostream* pstream__,
             const T2__& delta, const T3__& beta, const T4__& alpha,
             const T5__& gamma) const;
};

template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__, typename T5__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>,
                              stan::is_stan_scalar<T4__>,
                              stan::is_stan_scalar<T5__>>* = nullptr>
  Eigen::Matrix<stan::promote_args_t<T0__, stan::base_type_t<T1__>, T2__, T3__, T4__,
                     stan::promote_args_t<T5__>>, -1, 1>
  vensim_ode_func(const T0__& time, const T1__& outcome_arg__,
                  const T2__& delta, const T3__& beta, const T4__& alpha,
                  const T5__& gamma, std::ostream* pstream__) {
    using local_scalar_t__ =
            stan::promote_args_t<T0__, stan::base_type_t<T1__>, T2__, T3__,
                                 T4__, stan::promote_args_t<T5__>>;
    int current_statement__ = 0; 
    const auto& outcome = stan::math::to_ref(outcome_arg__);
    static constexpr bool propto__ = true;
    (void) propto__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      Eigen::Matrix<local_scalar_t__, -1, 1> dydt =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(2, DUMMY_VAR__);
      local_scalar_t__ prey = DUMMY_VAR__;
      current_statement__ = 24;
      prey = stan::model::rvalue(outcome, "outcome",
               stan::model::index_uni(1));
      local_scalar_t__ predator = DUMMY_VAR__;
      current_statement__ = 25;
      predator = stan::model::rvalue(outcome, "outcome",
                   stan::model::index_uni(2));
      local_scalar_t__ prey_death_rate = DUMMY_VAR__;
      current_statement__ = 26;
      prey_death_rate = ((beta * predator) * prey);
      local_scalar_t__ prey_birth_rate = DUMMY_VAR__;
      current_statement__ = 27;
      prey_birth_rate = (alpha * prey);
      local_scalar_t__ prey_dydt = DUMMY_VAR__;
      current_statement__ = 28;
      prey_dydt = (prey_birth_rate - prey_death_rate);
      local_scalar_t__ predator_birth_rate = DUMMY_VAR__;
      current_statement__ = 29;
      predator_birth_rate = ((delta * prey) * predator);
      local_scalar_t__ predator_death_rate = DUMMY_VAR__;
      current_statement__ = 30;
      predator_death_rate = (gamma * predator);
      local_scalar_t__ predator_dydt = DUMMY_VAR__;
      current_statement__ = 31;
      predator_dydt = (predator_birth_rate - predator_death_rate);
      current_statement__ = 32;
      stan::model::assign(dydt, prey_dydt,
        "assigning variable dydt", stan::model::index_uni(1));
      current_statement__ = 33;
      stan::model::assign(dydt, predator_dydt,
        "assigning variable dydt", stan::model::index_uni(2));
      current_statement__ = 34;
      return dydt;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    }
template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__, typename T5__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>,
                              stan::is_stan_scalar<T4__>,
                              stan::is_stan_scalar<T5__>>*>
Eigen::Matrix<stan::promote_args_t<T0__, stan::base_type_t<T1__>, T2__, T3__, T4__,
                     stan::promote_args_t<T5__>>, -1, 1>
vensim_ode_func_functor__::operator()(const T0__& time, const T1__& outcome,
                                      const T2__& delta, const T3__& beta,
                                      const T4__& alpha, const T5__& gamma,
                                      std::ostream* pstream__)  const
{
  return vensim_ode_func(time, outcome, delta, beta, alpha, gamma, pstream__);
}

template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__, typename T5__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>,
                              stan::is_stan_scalar<T4__>,
                              stan::is_stan_scalar<T5__>>*>
Eigen::Matrix<stan::promote_args_t<T0__, stan::base_type_t<T1__>, T2__, T3__, T4__,
                     stan::promote_args_t<T5__>>, -1, 1>
vensim_ode_func_odefunctor__::operator()(const T0__& time,
                                         const T1__& outcome,
                                         std::ostream* pstream__,
                                         const T2__& delta, const T3__& beta,
                                         const T4__& alpha, const T5__& gamma) 
const
{
  return vensim_ode_func(time, outcome, delta, beta, alpha, gamma, pstream__);
}


class prey_predator_draws2data_model final : public model_base_crtp<prey_predator_draws2data_model> {

 private:
  int n_t;
  double initial_time;
  std::vector<double> times; 
  
 
 public:
  ~prey_predator_draws2data_model() { }
  
  inline std::string model_name() const final { return "prey_predator_draws2data_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.30.1", "stancflags = --include-paths=/Users/hyunjimoon/Dropbox/BayesSD/ContinuousCode/explore/stan_files"};
  }
  
  
  prey_predator_draws2data_model(stan::io::var_context& context__,
                                 unsigned int random_seed__ = 0,
                                 std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "prey_predator_draws2data_model_namespace::prey_predator_draws2data_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 16;
      context__.validate_dims("data initialization","n_t","int",
           std::vector<size_t>{});
      n_t = std::numeric_limits<int>::min();
      
      
      current_statement__ = 16;
      n_t = context__.vals_i("n_t")[(1 - 1)];
      current_statement__ = 17;
      initial_time = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 17;
      initial_time = 0.0;
      current_statement__ = 18;
      stan::math::validate_non_negative_index("times", "n_t", n_t);
      current_statement__ = 19;
      times = 
        std::vector<double>(n_t, std::numeric_limits<double>::quiet_NaN());
      
      
      current_statement__ = 19;
      stan::model::assign(times, std::vector<double>{1, 2, 3, 4, 5, 6, 7, 8,
        9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20},
        "assigning variable times");
      current_statement__ = 20;
      stan::math::validate_non_negative_index("integrated_result", "n_t", n_t);
      current_statement__ = 21;
      stan::math::validate_non_negative_index("prey", "n_t", n_t);
      current_statement__ = 22;
      stan::math::validate_non_negative_index("predator", "n_t", n_t);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 0U;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "prey_predator_draws2data_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "prey_predator_draws2data_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      if (stan::math::logical_negation((stan::math::primitive_value(
            emit_transformed_parameters__) || stan::math::primitive_value(
            emit_generated_quantities__)))) {
        return ;
      } 
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      double alpha = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      alpha = stan::math::normal_rng(0.8, 0.1, base_rng__);
      double beta = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      beta = stan::math::normal_rng(0.05, 0.001, base_rng__);
      double delta = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      delta = stan::math::normal_rng(0.05, 0.001, base_rng__);
      double gamma = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      gamma = stan::math::normal_rng(0.8, 0.1, base_rng__);
      double sigma = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      sigma = stan::math::lognormal_rng(-6.907755278982137, 0.001,
                base_rng__);
      double prey__init = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 6;
      prey__init = 30;
      double predator__init = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 7;
      predator__init = 4;
      Eigen::Matrix<double, -1, 1> initial_outcome =
         Eigen::Matrix<double, -1, 1>::Constant(2,
           std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 9;
      stan::model::assign(initial_outcome, prey__init,
        "assigning variable initial_outcome", stan::model::index_uni(1));
      current_statement__ = 10;
      stan::model::assign(initial_outcome, predator__init,
        "assigning variable initial_outcome", stan::model::index_uni(2));
      std::vector<Eigen::Matrix<double, -1, 1>> integrated_result =
         std::vector<Eigen::Matrix<double, -1, 1>>(n_t, 
           Eigen::Matrix<double, -1, 1>::Constant(2,
             std::numeric_limits<double>::quiet_NaN()));
      current_statement__ = 11;
      stan::model::assign(integrated_result,
        stan::math::ode_rk45(vensim_ode_func_odefunctor__(), initial_outcome,
          initial_time, times, pstream__, delta, beta, alpha, gamma),
        "assigning variable integrated_result");
      std::vector<double> prey =
         std::vector<double>(n_t, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 12;
      stan::model::assign(prey,
        stan::model::rvalue(integrated_result, "integrated_result",
          stan::model::index_omni(), stan::model::index_uni(1)),
        "assigning variable prey");
      std::vector<double> predator =
         std::vector<double>(n_t, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 13;
      stan::model::assign(predator,
        stan::model::rvalue(integrated_result, "integrated_result",
          stan::model::index_omni(), stan::model::index_uni(2)),
        "assigning variable predator");
      Eigen::Matrix<double, -1, 1> predator_obs =
         Eigen::Matrix<double, -1, 1>::Constant(20,
           std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 14;
      stan::model::assign(predator_obs,
        stan::math::to_vector(
          stan::math::lognormal_rng(predator, sigma, base_rng__)),
        "assigning variable predator_obs");
      Eigen::Matrix<double, -1, 1> prey_obs =
         Eigen::Matrix<double, -1, 1>::Constant(20,
           std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 15;
      stan::model::assign(prey_obs,
        stan::math::to_vector(
          stan::math::lognormal_rng(prey, sigma, base_rng__)),
        "assigning variable prey_obs");
      out__.write(alpha);
      out__.write(beta);
      out__.write(delta);
      out__.write(gamma);
      out__.write(sigma);
      out__.write(prey__init);
      out__.write(predator__init);
      out__.write(initial_outcome);
      for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= n_t; ++sym2__) {
          out__.write(integrated_result[(sym2__ - 1)][(sym1__ - 1)]);
        }
      }
      out__.write(prey);
      out__.write(predator);
      out__.write(predator_obs);
      out__.write(prey_obs);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(VecVar& params_r__, VecI& params_i__,
                                   VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"alpha", "beta", "delta", "gamma",
      "sigma", "prey__init", "predator__init", "initial_outcome",
      "integrated_result", "prey", "predator", "predator_obs", "prey_obs"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
      std::vector<size_t>{}, std::vector<size_t>{}, std::vector<size_t>{
      }, std::vector<size_t>{}, std::vector<size_t>{}, std::vector<size_t>{
      }, std::vector<size_t>{static_cast<size_t>(2)},
      std::vector<size_t>{static_cast<size_t>(n_t), static_cast<size_t>(2)},
      std::vector<size_t>{static_cast<size_t>(n_t)},
      std::vector<size_t>{static_cast<size_t>(n_t)},
      std::vector<size_t>{static_cast<size_t>(20)},
      std::vector<size_t>{static_cast<size_t>(20)}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "alpha");
      param_names__.emplace_back(std::string() + "beta");
      param_names__.emplace_back(std::string() + "delta");
      param_names__.emplace_back(std::string() + "gamma");
      param_names__.emplace_back(std::string() + "sigma");
      param_names__.emplace_back(std::string() + "prey__init");
      param_names__.emplace_back(std::string() + "predator__init");
      for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "initial_outcome" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= n_t; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "integrated_result" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            } 
          }
        } 
      }
      for (int sym1__ = 1; sym1__ <= n_t; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "prey" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= n_t; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "predator" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= 20; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "predator_obs" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= 20; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "prey_obs" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "alpha");
      param_names__.emplace_back(std::string() + "beta");
      param_names__.emplace_back(std::string() + "delta");
      param_names__.emplace_back(std::string() + "gamma");
      param_names__.emplace_back(std::string() + "sigma");
      param_names__.emplace_back(std::string() + "prey__init");
      param_names__.emplace_back(std::string() + "predator__init");
      for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "initial_outcome" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= n_t; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "integrated_result" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            } 
          }
        } 
      }
      for (int sym1__ = 1; sym1__ <= n_t; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "prey" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= n_t; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "predator" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= 20; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "predator_obs" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= 20; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "prey_obs" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"beta\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"delta\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"gamma\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"prey__init\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"predator__init\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"initial_outcome\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(2) + "},\"block\":\"generated_quantities\"},{\"name\":\"integrated_result\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n_t) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(2) + "}},\"block\":\"generated_quantities\"},{\"name\":\"prey\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n_t) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"predator\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n_t) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"predator_obs\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(20) + "},\"block\":\"generated_quantities\"},{\"name\":\"prey_obs\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(20) + "},\"block\":\"generated_quantities\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"beta\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"delta\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"gamma\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"prey__init\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"predator__init\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"initial_outcome\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(2) + "},\"block\":\"generated_quantities\"},{\"name\":\"integrated_result\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n_t) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(2) + "}},\"block\":\"generated_quantities\"},{\"name\":\"prey\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n_t) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"predator\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n_t) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"predator_obs\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(20) + "},\"block\":\"generated_quantities\"},{\"name\":\"prey_obs\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(20) + "},\"block\":\"generated_quantities\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 0;
      const size_t num_transformed = emit_transformed_parameters * 0;
      const size_t num_gen_quantities = emit_generated_quantities * 
  ((((((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 2) + (n_t * 2)) + n_t) + n_t)
     + 20) + 20);
      const size_t num_to_write = num_params__ + num_transformed +
        num_gen_quantities;
      std::vector<int> params_i;
      vars = Eigen::Matrix<double, Eigen::Dynamic, 1>::Constant(num_to_write,
        std::numeric_limits<double>::quiet_NaN());
      write_array_impl(base_rng, params_r, params_i, vars,
        emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 0;
      const size_t num_transformed = emit_transformed_parameters * 0;
      const size_t num_gen_quantities = emit_generated_quantities * 
  ((((((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 2) + (n_t * 2)) + n_t) + n_t)
     + 20) + 20);
      const size_t num_to_write = num_params__ + num_transformed +
        num_gen_quantities;
      vars = std::vector<double>(num_to_write,
        std::numeric_limits<double>::quiet_NaN());
      write_array_impl(base_rng, params_r, params_i, vars,
        emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }

  inline void transform_inits(const stan::io::var_context& context,
                              std::vector<int>& params_i,
                              std::vector<double>& vars,
                              std::ostream* pstream__ = nullptr) const {
     constexpr std::array<const char*, 0> names__{};
      const std::array<Eigen::Index, 0> constrain_param_sizes__{};
      const auto num_constrained_params__ = std::accumulate(
        constrain_param_sizes__.begin(), constrain_param_sizes__.end(), 0);
    
     std::vector<double> params_r_flat__(num_constrained_params__);
     Eigen::Index size_iter__ = 0;
     Eigen::Index flat_iter__ = 0;
     for (auto&& param_name__ : names__) {
       const auto param_vec__ = context.vals_r(param_name__);
       for (Eigen::Index i = 0; i < constrain_param_sizes__[size_iter__]; ++i) {
         params_r_flat__[flat_iter__] = param_vec__[i];
         ++flat_iter__;
       }
       ++size_iter__;
     }
     vars.resize(num_params_r__);
     transform_inits_impl(params_r_flat__, params_i, vars, pstream__);
    } // transform_inits() 
     }; } 
using stan_model = prey_predator_draws2data_model_namespace::prey_predator_draws2data_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return prey_predator_draws2data_model_namespace::profiles__;
}

#endif


